const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function setup(overrides={}){const user={_id:'driver',role:'driver',kycLevel:'full',registrationStatus:'pending',isActive:false,...overrides},calls=[];const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../services/driverActivation.js'),'utf8'),{module,require:()=>({findOneAndUpdate:async(filter,update)=>{calls.push({filter,update});return {...user,...update.$set};}})});return {user,calls,activate:module.exports.activateFullKycDriver};}
test('full KYC activates a pending driver even before the separately required fee',async()=>{const {user,calls,activate}=setup({registrationPaid:false});await activate(user);assert.equal(user.isActive,true);assert.equal(user.registrationStatus,'approved');assert.equal(user.registrationPaid,false);assert.equal(calls[0].filter.activationBlocked.$ne,true);});
test('approval is idempotent and never reactivates a suspended, deleted or incomplete account',async()=>{for(const override of [{role:'client'},{kycLevel:'basic'},{deletedAt:new Date()},{activationBlocked:true},{registrationStatus:'approved',isActive:false}]){const {user,calls,activate}=setup(override);await activate(user);assert.equal(calls.length,0);assert.equal(user.isActive,false);}const {user,calls,activate}=setup();await activate(user);await activate(user);assert.equal(calls.length,1);});
test('full KYC approval activates immediately through the review controller',async()=>{const {user,activate}=setup(),module={exports:{}},record={_id:'kyc',userId:'driver'};const dependencies={'mongoose':{isValidObjectId:()=>true,startSession:async()=>({withTransaction:async fn=>fn(),endSession:async()=>{}})},'../models/DriverKyc':{findById:async()=>record,findOneAndUpdate:async()=>record},'../models/PassengerKyc':{},'../models/User':{findByIdAndUpdate:async()=>user},'../services/driverActivation':{activateFullKycDriver:activate},'../services/referralService':{trySettleReferral:async()=>{}},'../services/auditService':{log:async()=>{}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../controllers/kycController.js'),'utf8'),{module,require:name=>dependencies[name],Date});let body;await module.exports.adminReview({params:{type:'driver',id:'kyc'},body:{status:'approved'},user:{id:'staff',role:'admin'}},{json:payload=>{body=payload;}});assert.equal(user.isActive,true);assert.match(body.message,/approved/);});
test('account snapshot excludes secrets and fetches KYC and driver profile together',async()=>{const module={exports:{}},selections=[];const query=(data)=>({select(fields){selections.push(fields);return this;},populate(){return this;},lean:async()=>data,then(resolve){return Promise.resolve(data).then(resolve);}});const account={_id:'driver',role:'driver',isVerified:true,kycLevel:'full',isActive:true,registrationPaid:false,toObject(){return {_id:this._id,role:this.role,isVerified:this.isVerified,kycLevel:this.kycLevel,isActive:this.isActive,registrationPaid:false};}};const dependencies={'../models/User':{findById:()=>query(account)},'../models/DriverKyc':{findOne:()=>query({status:'approved'})},'../models/DriverProfile':{findOne:()=>query({plateNumber:'RAA123'})}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../controllers/userController.js'),'utf8'),{module,require:name=>dependencies[name]||{}});let payload;await module.exports.getMe({user:{id:'driver'}},{json:value=>{payload=value;},status(){return this;}});assert.equal(payload.data.driverProfile.plateNumber,'RAA123');assert.equal(payload.data.onboarding.kycStatus,'approved');assert.equal(payload.data.onboarding.registrationFeeRequired,true);assert.equal(payload.data.onboarding.registrationPaid,false);assert.ok(!selections[0].split(' ').some(key=>['password','otpToken','twoFactorSecret','registrationPaypackRef'].includes(key)));});
test('welcome status is accessible while operational APIs still require phone and fee',async()=>{
 const user={_id:'driver',role:'driver',kycLevel:'full',registrationStatus:'approved',isActive:true,isVerified:true,registrationPaid:false};const module={exports:{}};const dependencies={'jsonwebtoken':{verify:()=>({id:'driver'})},'../models/User':{findById:()=>({select(){return this;},populate:async()=>user})},'../models/Session':{},'../services/driverActivation':{activateFullKycDriver:async()=>user}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../middleware/authMiddleware.js'),'utf8'),{module,require:name=>dependencies[name]||{},process:{env:{JWT_SECRET:'test'}},Date});let code,next=0;const req={headers:{authorization:'Bearer token'}},res={status(value){code=value;return this;},json(){}};
 await module.exports.protect(req,res,()=>next++);assert.equal(code,403);assert.equal(next,0);
 await module.exports.protectOnboardingStatus(req,res,()=>next++);assert.equal(next,1);
 user.registrationPaid=true;await module.exports.protect(req,res,()=>next++);assert.equal(next,2);
 user.isVerified=false;await module.exports.protect(req,res,()=>next++);assert.equal(code,403);assert.equal(next,2);
 user.isVerified=true;user.kycLevel='basic';await module.exports.protect(req,res,()=>next++);assert.equal(code,403);assert.equal(next,2);
});
