const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PERMISSIONS}=require('../constants/staffRoles'),{validateRoleGrant,roleAccountType,matchesRole}=require('../services/rolePermissions'),{validateFieldReviews}=require('../services/kycFieldReview');
test('all route authorization permissions belong to catalog',()=>{for(const f of fs.readdirSync(path.join(__dirname,'../routes'))){if(!f.endsWith('.js'))continue;const source=fs.readFileSync(path.join(__dirname,'../routes',f),'utf8');for(const m of source.matchAll(/authorize\(([^)]*)\)/g))for(const p of m[1].matchAll(/['"]([a-z_]+:[a-z_]+)['"]/g))assert.ok(PERMISSIONS.includes(p[1]),`${f}: ${p[1]}`);}});
test('role manager cannot grant access beyond own permissions',()=>{const actor={role:'admin',roleId:{permissions:['role:view','role:manage','user:view']}};assert.deepEqual(validateRoleGrant(actor,['user:view']),['user:view']);assert.throws(()=>validateRoleGrant(actor,['wallet:adjust']),e=>e.status===403);assert.throws(()=>validateRoleGrant(actor,['does:not_exist']),e=>e.status===400);assert.deepEqual(validateRoleGrant({role:'superadmin'},PERMISSIONS),PERMISSIONS);});
test('custom role cannot select ownership or driver identity',()=>{assert.equal(roleAccountType({name:'fleet_reviewer'}),'manager');assert.equal(matchesRole({name:'fleet_reviewer'},'manager'),true);assert.equal(matchesRole({name:'fleet_reviewer'},'superadmin'),false);assert.equal(matchesRole({name:'fleet_reviewer'},'driver'),false);});
test('approval requires every submitted field reviewed',()=>{const record={nationalIdNumber:'123',selfie:'file'};assert.throws(()=>validateFieldReviews(['nationalIdNumber','selfie'],record,[{key:'selfie',status:'approved'}],'approved'),/every submitted/);assert.equal(validateFieldReviews(['nationalIdNumber','selfie'],record,[{key:'selfie',status:'approved'},{key:'nationalIdNumber',status:'approved'}],'approved').length,2);});
test('reject invalid duplicates and unjustified corrections',()=>{for(const r of [[{key:'password',status:'approved'}],[{key:'selfie',status:'approved'},{key:'selfie',status:'approved'}],[{key:'selfie',status:'correction',reason:'bad'}],[{key:'optional',status:'approved'}]])assert.throws(()=>validateFieldReviews(['selfie','optional'],{selfie:'file'},r,'correction'));assert.equal(validateFieldReviews(['selfie'],{selfie:'file'},[{key:'selfie',status:'correction',reason:'Upload clearer image'}],'correction')[0].reason,'Upload clearer image');});
test('expired documents cannot be approved',()=>{assert.throws(()=>validateFieldReviews(['insuranceExpiresAt'],{insuranceExpiresAt:new Date(0)},[{key:'insuranceExpiresAt',status:'approved'}],'approved'),/Expired/);});

const vm=require('node:vm');
function reviewController({record={_id:'kyc',userId:'user',nationalIdNumber:'123',updatedAt:new Date('2026-10-01')},updated=record,account={_id:'user',role:'client'},referralError=false}={}){
  const calls=[],session={withTransaction:async(fn)=>{calls.push('transaction');await fn();},endSession:async()=>calls.push('end')};
  const model={findById:async()=>record,findOneAndUpdate:async(query,update,options)=>{calls.push({query,update,options});return updated;}};
  const deps={'mongoose':{isValidObjectId:()=>true,startSession:async()=>session},'../models/PassengerKyc':model,'../models/DriverKyc':model,'../models/User':{findByIdAndUpdate:async(id,update,options)=>{calls.push({id,update,options});return account;}},'../services/kycFieldReview':{validateFieldReviews},'../services/driverActivation':{activateFullKycDriver:async()=>{}},'../services/referralService':{trySettleReferral:async()=>{if(referralError)throw new Error('provider failure');}},'../services/auditService':{log:async()=>calls.push('audit')}};
  const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../controllers/kycController.js'),'utf8'),{module,require:name=>deps[name],Date,console:{error(){}}});
  return {review:module.exports.adminReview,calls,session};
}
function response(){return {code:200,status(code){this.code=code;return this;},json(body){this.body=body;}};}
const reviewRequest=(body)=>({params:{type:'passenger',id:'kyc'},user:{id:'staff',role:'admin'},body});
test('stale KYC review returns conflict without updating user',async()=>{const {review,calls}=reviewController({updated:null});const res=response();await review(reviewRequest({status:'approved',expectedUpdatedAt:'2026-10-01',fieldReviews:[{key:'nationalIdNumber',status:'approved'}]}),res);assert.equal(res.code,409);assert.ok(!calls.some(c=>c.id));assert.equal(calls.at(-1),'end');});
test('correction commits basic KYC and takes user offline in the same transaction',async()=>{const {review,calls,session}=reviewController();const res=response();await review(reviewRequest({status:'correction',remarks:'Retake the ID image',expectedUpdatedAt:'2026-10-01',fieldReviews:[{key:'nationalIdNumber',status:'correction',reason:'Number is illegible'}]}),res);assert.equal(res.code,200);const writes=calls.filter(c=>c.options);assert.equal(writes.length,2);assert.ok(writes.every(c=>c.options.session===session));assert.equal(writes[1].update.kycLevel,'basic');assert.equal(writes[1].update.isOnline,false);});
test('invalid KYC version fails before a write',async()=>{const {review,calls}=reviewController();const res=response();await review(reviewRequest({status:'approved',expectedUpdatedAt:'invalid'}),res);assert.equal(res.code,400);assert.equal(calls.length,0);});
test('referral failure reports saved review with warning instead of upload-like false failure',async()=>{const {review}=reviewController({referralError:true});const res=response();await review(reviewRequest({status:'approved',expectedUpdatedAt:'2026-10-01',fieldReviews:[{key:'nationalIdNumber',status:'approved'}]}),res);assert.equal(res.code,200);assert.equal(res.body.warnings.length,1);});

function adminControllerTest({roleRecord=null,actor={id:'admin',role:'superadmin'}}={}){
  let created,assigned;const account={_id:'user',role:'client'};
  const dependencies={'../services/rolePermissions':require('../services/rolePermissions'),'../services/reportAccess':require('../services/reportAccess'),'../constants/staffRoles':require('../constants/staffRoles'),'mongoose':{isValidObjectId:()=>true},'../models/User':{exists:async()=>false,findById:async()=>account,create:async(data)=>{created=data;return data;}},'../models/Role':{findById:async()=>roleRecord},'../services/userService':{updateUser:async(id,data)=>{assigned=data;return data;}},'bcrypt':{hash:async()=> 'hashed'},'../services/auditService':{log:async()=>{}}};
  const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../controllers/adminController.js'),'utf8'),{module,require:name=>dependencies[name]||{},Date});
  return {controller:module.exports,actor,getCreated:()=>created,getAssigned:()=>assigned};
}
test('custom staff role is assigned during user creation using manager identity',async()=>{const t=adminControllerTest({roleRecord:{_id:'role',name:'kyc_reviewer',permissions:['admin:access','kyc:view']}}),res=response();await t.controller.createUserAccount({body:{firstName:'Test',lastName:'Staff',phone:'+250780000000',password:'secure-pass',role:'manager',roleId:'role'},user:t.actor},res);assert.equal(res.code,201);assert.equal(t.getCreated().role,'manager');assert.equal(t.getCreated().roleId,'role');});
test('nonexistent custom role assignment cannot silently clear user role',async()=>{const t=adminControllerTest(),res=response();await t.controller.assignUserRole({params:{id:'user'},body:{role:'manager',roleId:'missing'},user:t.actor},res);assert.equal(res.code,400);assert.equal(t.getAssigned(),undefined);});
test('user creation cannot grant a custom role with higher non-reporting access',async()=>{const t=adminControllerTest({actor:{id:'admin',role:'admin',roleId:{permissions:['user:create','admin:access']}},roleRecord:{_id:'role',name:'wallet_ops',permissions:['admin:access','wallet:adjust']}}),res=response();await t.controller.createUserAccount({body:{firstName:'Test',lastName:'Staff',phone:'+250780000000',password:'secure-pass',role:'manager',roleId:'role'},user:t.actor},res);assert.equal(res.code,403);assert.equal(t.getCreated(),undefined);});
test('Swagger exposes versioned per-field review and assignable role schema',()=>{const spec=require('../swagger');assert.ok(spec.paths['/api/roles/permissions'].get);assert.ok(spec.paths['/api/roles/assignable'].get);assert.ok(spec.paths['/api/admin/kyc/{type}/{id}'].get);assert.ok(spec.components.schemas.KycReviewRequest.properties.expectedUpdatedAt);assert.deepEqual(spec.components.schemas.KycFieldDecision.properties.status.enum,['approved','correction']);});
